# Generated by Django 5.2.10 on 2026-03-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogovirText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('style', models.CharField(choices=[('LeftBold', 'Left Bold'), ('LeftSemiBold', 'Left Semi Bold'), ('LeftNormal', 'Left Normal')], max_length=20)),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'Dogovir Text',
                'verbose_name_plural': 'Dogovir Texts',
                'ordering': ['order'],
            },
        ),
    ]
