# Generated by Django 5.2.10 on 2026-03-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSpecial',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Author Special',
                'verbose_name_plural': 'Author Specials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Complex',
                'verbose_name_plural': 'Complexes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KramItem',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('additional', 'Additional'), ('drinks', 'Drinks'), ('massagers', 'Massagers'), ('snacks', 'Snacks'), ('souvenirs', 'Souvenirs')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kram Item',
                'verbose_name_plural': 'Kram Items',
                'ordering': ['section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['name'],
            },
        ),
    ]
