# Generated by Django 5.2.10 on 2026-03-29 16:25

import django.db.models.deletion
import guests.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.CharField(default=guests.models.generate_short_uuid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50, verbose_name='Alias')),
                ('source', models.CharField(max_length=30, verbose_name='Source')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Full name')),
                ('birthday', models.CharField(blank=True, max_length=20, verbose_name='Birthday')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('document', models.CharField(blank=True, max_length=100, verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id_snapshot', models.CharField(db_index=True, max_length=12)),
                ('guest_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10, verbose_name='Action')),
                ('actor_label', models.CharField(blank=True, help_text='Username snapshot at the time of the action', max_length=150, verbose_name='Actor label')),
                ('diff', models.JSONField(default=dict, verbose_name='Diff')),
                ('snapshot', models.JSONField(default=dict, verbose_name='Snapshot')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='guests.guest', verbose_name='Guest')),
            ],
            options={
                'verbose_name': 'Guest log',
                'verbose_name_plural': 'Guest logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['guest_id_snapshot', '-timestamp'], name='guests_gues_guest_i_3c41e6_idx'), models.Index(fields=['actor', '-timestamp'], name='guests_gues_actor_i_5e04fc_idx'), models.Index(fields=['action', '-timestamp'], name='guests_gues_action_e7bb4b_idx')],
            },
        ),
    ]
