# Generated by Django 5.2.10 on 2026-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='birthday',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
    ]
