# Generated by Django 5.2.10 on 2026-07-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetoken',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activetoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activetoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activetoken',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activetoken',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
