# Generated by Django 5.2.10 on 2026-07-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_activetoken_browser_activetoken_device_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetoken',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='activetoken',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='activetoken',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='activetoken',
            name='os',
        ),
        migrations.RemoveField(
            model_name='activetoken',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='user_agent',
        ),
    ]
