# Generated by Django 5.2.10 on 2026-03-29 16:25

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=bookings.models.generate_short_uuid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('house', models.CharField(choices=[('family', 'Family'), ('left', 'Left'), ('right', 'Right')], max_length=100)),
                ('source', models.CharField(choices=[('i', 'Instagram'), ('tg', 'Telegram'), ('v', 'Viber'), ('w', 'WhatsApp'), ('t', 'Phone'), ('bot', 'Bot')], max_length=100)),
                ('type', models.CharField(choices=[('house', 'House'), ('lazni', 'Lazni'), ('pool', 'Pool')], max_length=100)),
                ('extensions', models.JSONField(blank=True, default=list)),
                ('lazni', models.JSONField(blank=True, default=dict)),
                ('dogovir', models.JSONField(blank=True, default=bookings.models.default_dogovir)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('prepayment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalcost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='guests.guest')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id_snapshot', models.CharField(db_index=True, max_length=20)),
                ('booking_label_snapshot', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('diff', models.JSONField(default=dict)),
                ('snapshot', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_logs', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='bookings.booking')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
