# Generated by Django 5.2.10 on 2026-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(blank=True, choices=[('i', 'Instagram'), ('tg', 'Telegram'), ('v', 'Viber'), ('w', 'WhatsApp'), ('t', 'Phone'), ('b', 'Bot')], max_length=100, null=True),
        ),
    ]
