# Generated by Django 5.2.10 on 2026-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gcal_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
