# Generated by Django 5.2.10 on 2026-07-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_gcal_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
