# Generated by Django 5.2.10 on 2026-04-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_analytics', 'Can view analytics'), ('view_reports', 'Can view reports'), ('view_export', 'Can export'), ('view_dogovir', 'Can view dogovir'), ('requires_pwa', 'Requires PWA')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_stats_api_key', models.CharField(max_length=255)),
                ('bot_stats_api_key', models.CharField(max_length=255)),
            ],
        ),
    ]
