# Generated by Django 5.2.10 on 2026-07-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_requestlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_analytics', 'Can view analytics'), ('view_reports', 'Can view reports'), ('view_export', 'Can export'), ('view_contract', 'Can view contract'), ('show_contract', 'Can show contract to guests'), ('requires_pwa', 'Requires PWA'), ('view_personal_data', 'View guests personal data')]},
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
